# Generated by Django 5.2.17 on 2026-09-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_alter_album_album_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='song',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='songs/'),
        ),
        migrations.AddField(
            model_name='song',
            name='duration',
            field=models.CharField(blank=True, default='3:30', max_length=20),
        ),
        migrations.AlterField(
            model_name='album',
            name='album_logo',
            field=models.FileField(blank=True, null=True, upload_to='album_logos/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='file_type',
            field=models.CharField(blank=True, default='mp3', max_length=10),
        ),
    ]
